#version: '3.8'
services:
  web:
    #build: build image Dockerfile context la thu muc
    build:
      context: .
      dockerfile: Dockerfile
    #environment: bien moi truong de anh xa application.yml hoac 1 so database can password
    environment:
      spring_data_url: jdbc:mysql://mysql:3306/redis
      spring_data_username: root
      spring_data_password: Manh2004
    ports:
      - 8080:8080
    #depends_on: phu thuoc vao service nao, hay chay service redis, my sql trc
    depends_on:
      - redis
      - mysql
  redis:
    #image: image
    image: redis:7.4.2
    environment:
      redis_host: redis
      redis_port: 6379
    ports:
      - 6379:6379
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Manh2004
      MYSQL_DATABASE: redis
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  mysql_data:
