spring:
  application:
    name: redis
  datasource:
    username: root
    password: Manh2004
    url: jdbc:mysql://host.docker.internal:3306/redis
    #localhost
  jpa:
    hibernate:
      ddl-auto: none
    #      none, update, auto-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  data:
    redis:
      host: host.docker.internal
      #localhost
      port: 6379
  cache:
    type: redis

#  docker pull redis:7.4.2
#  docker run -d --name redis-server -p 6379:6379 redis:7.4.2

